### ISSUE TITLE
Sieve broken

### ISSUE THREAD

**Issue by Android995** [jayugg/SmithingPlus#2] opened 2024-12-01 04:09 UTC
v1.1.3 #v1.19.8
When trying to craft Parcment with a sieve, a bug occurs, ghostly items are obtained, crafting does not occur and the durability of the sieve does not decrease.
The durability changes only visually, but if you move the items, they disappear and the durability is 199 again.
The durability of the sieve does not drop below 199.
When I try to craft again on the server, I am thrown out of the server, and sometimes due to a kick, the items are duplicated.
In a single world, the same problems, only there are no kicks.

The problem is in smithingplus_1.1.3, which breaks the vanilla sieve, being the only one in the folder.

**Comment by Orman-Grandclaw** [comment] 2024-12-01 15:51
A similar issue seems to happen with the wooden pan from wild farming revival I think.

**Comment by Android995** [comment] 2024-12-02 14:48
Temporary solution
If "EnableToolRecovery": false, the file SmithingPlus.json in VintagestoryData/ModConfig
sieve correct craft

**Comment by Orman-Grandclaw** [comment] 2024-12-02 15:25
That kinda defeats the whole point of this mod though. It would be better if there was some way to specifically add things that are excluded.

**Comment by jacopouggeri** [comment] 2024-12-04 11:37
They are excluded, the problem is the crash is happening before the exclusion check happens, it has to do with how their durability works. It will be fixed when I find the time.

**Comment by jacopouggeri** [comment] 2024-12-04 11:39
The config has a wildcard selector for included tools, only those will pass the check, but before that, there is a check if the item is about to be destroyed, to proceed only in that case, that's what's crashing

**Comment by jacopouggeri** [comment] 2024-12-04 11:40
This is a duplicate of https://github.com/jayugg/SmithingPlus/issues/1

**Comment by jacopouggeri** [comment] 2024-12-04 11:42
Duplicate of https://github.com/jayugg/SmithingPlus/issues/1

**Comment by jacopouggeri** [comment] 2024-12-05 09:13
Duplicate of #1

**Closed** 2024-12-06 16:24 UTC
